### ISSUE TITLE
Meeting @ Thode on Saturday and Sunday

### ISSUE THREAD

**Issue by bobotie23** [Edwardhyw/smartVault#116]
Try to combine the modules together and do some testing. Finish the video recording for Rev0 demo. VERY IMPORTANT!!!

**Comment by Edwardhyw** [comment]
1. Functional test for module image processing                     
2. Functional test for module file storage                               
3. Functional test for module UI
4. Integrate image processing and file storage module
5. Integrate software module
6. Combine hardware and software

**Comment by Edwardhyw** [comment]
Sunday Agenda:
1. recording demo video
2. rehearse presentation video
