### ISSUE TITLE
Team 23 VnV Report Review - Ambiguous "change due to testing"

### ISSUE THREAD

**Issue by LemonU-mcmaster** [Edwardhyw/smartVault#124]
The second "change due to testing" documented in section 7 states that:
> "[users are] only required to interact with the user interface which has adapted to user feedback to improve usability".

From the statement, a reader can tell vaguely that something has changed in the UI for better usability, but the change itself is not apparent.

What did you actually change in the UI to address usability concerns? Did you perform some aethetics work? Did you re-adjust the layout of our UI? Did you use a different style of graphical components? These are some stuff you can write about to be more specific on what you changed. It's doesn't have to be comprehensive in a way that you use every single word possible to document your changes in full-depth, but at least it should be enough to tell the reader that what aspects of the system has been altered or what is the qualitative methodology you used in approaching the changes.

**Comment by LemonU-mcmaster** [comment]
@samm82

**Comment by Edwardhyw** [comment]
Thanks, have updated
