### ISSUE TITLE
Team 23 VnV Report Review - Possible Additional Test Cases

### ISSUE THREAD

**Issue by Womfidence** [Edwardhyw/smartVault#126]
For the most part, your written test cases are well written and explained, and you have good examples and data showing the outputs/results of your tests. However, looking through your VnV Plan and SRS, I feel like you are missing some possibly important test scenarios for your system. You correctly test the functionality of several parts of your system, but you don't seem to test for certain scenarios or unexpected inputs. For example, under the IPR1 requirement, you test for correct identification of a human's body, which is reflected and tested well in your VnV Report. However, that is the only test performed for that requirement, where I believe additional test cases could prove to be useful - What if something else, similar to a body gets identified incorrectly, like a cat or a dog? What occurs if there are two people in the frame? Additional test cases like these to check the robustness of your system could prove very helpful in the development of your system as a whole.

**Comment by Edwardhyw** [comment]
The idea is that we assume only human would move things in the room, so misidentifying is not an issue of our concern. We just need to make sure that it can accurately identify human. Also, multiple people in the frame is not a problem as we only concern about if human is present in the room.
