### ISSUE TITLE
Review-VnVPlan-Team25

### ISSUE THREAD

**Issue by ahmed-nazir** [Edwardhyw/smartVault#80]
The reviewer's capstone group TA is @tomashetMcMaster.

In your functional requirement test IPR3-1 it refers to detecting objects that come into environment, in your SRS document it mentions for IPR3 that the system should be able to identify all the "small" items being exposed. It might be better to have the word "small" be more specific and put some metrics to it e.g items smaller than 3cmx3cmx3cm, this would also make the functional requirement test more measurable.

**Comment by Edwardhyw** [comment]
we have updated our SRS document to reflect on our changes
