### ISSUE TITLE
Review-VnVPlan-Team25

### ISSUE THREAD

**Issue by ahmed-nazir** [Edwardhyw/smartVault#81]
The reviewer's capstone group TA is @tomashetMcMaster.

For functional requirement test IPR5-1 it refers to having the system detect between two different objects, and in the SRS document (IPR5) it mentions that it will do this by looking for the item shape, item color and item size, I think this functional requirement test could be broken down into 3 components one test to see if it can differentiate shape, one for size and one for color.

**Comment by Edwardhyw** [comment]
we have changed our algorithm and updated all documents.
