### ISSUE TITLE
Review-VnVPlan-Team25

### ISSUE THREAD

**Issue by TioluwaB** [Edwardhyw/smartVault#90]
The reviewer's capstone group TA is @tomashetMcMaster.

In section 6.2 Demonstration Plan although all the test steps makes sense and meet the requirements, I believe that some of the steps can be given a bit more descriptive and also be given a title to help the reader under what is going in each test case. For example for test #4 it can be given title called "Testing camera tracking with Human Movement". This will give the user a general idea of what to expect from the test.

**Comment by Edwardhyw** [comment]
we have added more details, thanks
